-- The Wild Oasis – Supabase backend schema
-- Run this in the Supabase SQL Editor to create tables and seed settings.
-- Column names use camelCase to match the app's API (src/services/*.js).

-- =============================================================================
-- 1. GUESTS
-- =============================================================================
CREATE TABLE IF NOT EXISTS guests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullName" TEXT NOT NULL,
  email TEXT NOT NULL,
  nationality TEXT,
  "nationalID" TEXT,
  "countryFlag" TEXT
);

-- =============================================================================
-- 2. CABINS
-- =============================================================================
CREATE TABLE IF NOT EXISTS cabins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  "maxCapacity" INT NOT NULL,
  "regularPrice" NUMERIC NOT NULL,
  discount NUMERIC NOT NULL DEFAULT 0,
  image TEXT,
  description TEXT
);

-- =============================================================================
-- 3. SETTINGS (single row, id = 1)
-- =============================================================================
CREATE TABLE IF NOT EXISTS settings (
  id INT PRIMARY KEY CHECK (id = 1),
  "minBookingLength" INT NOT NULL DEFAULT 3,
  "maxBookingLength" INT NOT NULL DEFAULT 30,
  "maxGuestsPerBooking" INT NOT NULL DEFAULT 10,
  "breakfastPrice" NUMERIC NOT NULL DEFAULT 15
);

-- Seed the one required settings row (app expects exactly one row with id = 1)
INSERT INTO settings (id, "minBookingLength", "maxBookingLength", "maxGuestsPerBooking", "breakfastPrice")
VALUES (1, 3, 30, 10, 15)
ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- 4. BOOKINGS (after guests and cabins exist)
-- =============================================================================
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "startDate" DATE NOT NULL,
  "endDate" DATE NOT NULL,
  "numNights" INT NOT NULL,
  "numGuests" INT NOT NULL,
  "cabinPrice" NUMERIC NOT NULL,
  "extrasPrice" NUMERIC NOT NULL DEFAULT 0,
  "totalPrice" NUMERIC NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('unconfirmed', 'checked-in', 'checked-out')),
  "hasBreakfast" BOOLEAN NOT NULL DEFAULT false,
  "isPaid" BOOLEAN NOT NULL DEFAULT false,
  observations TEXT,
  "cabinId" BIGINT NOT NULL REFERENCES cabins(id) ON DELETE CASCADE,
  "guestId" BIGINT NOT NULL REFERENCES guests(id) ON DELETE CASCADE
);

-- Optional: indexes for common filters/sorts
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_start_date ON bookings("startDate");
CREATE INDEX IF NOT EXISTS idx_bookings_created_at ON bookings(created_at);

-- =============================================================================
-- 5. STORAGE BUCKETS (create in Dashboard: Storage → New bucket)
-- =============================================================================
-- Create these in Supabase Dashboard → Storage:
--   - cabin-images  (public) – cabin photos
--   - avatars       (public) – user profile avatars
-- Then in Storage → Policies, allow public read (and appropriate write for auth).

-- =============================================================================
-- 6. ROW LEVEL SECURITY (optional but recommended for production)
-- =============================================================================
-- Enable RLS on tables and add policies so only authenticated users can read/write.
-- Example for bookings (adjust to your auth rules):
-- ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow all for authenticated" ON bookings FOR ALL USING (auth.role() = 'authenticated');
-- Repeat for cabins, guests, settings as needed.
